In [1]:
#MNIST classification

from keras import models
from keras import layers
from keras.datasets import mnist
from keras.utils import to_categorical

Using TensorFlow backend.


In [2]:
(train_images, train_labels), (test_images, test_labels)= mnist.load_data()

In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
type(train_labels)

numpy.ndarray

In [6]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
test_images.shape

(10000, 28, 28)

In [8]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [9]:
test_labels.shape

(10000,)

In [10]:
network= models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))

In [11]:
network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'] )

In [12]:
#reshaping the images in the range of [0,1]

train_images=train_images.reshape(60000, (28*28))
test_images=test_images.reshape(10000, (28*28))

In [13]:
train_images=train_images.astype('float32')/255.0
test_images=test_images.astype('float32')/255.0

In [14]:
train_labels= to_categorical(train_labels)
test_labels= to_categorical(test_labels)

In [15]:
network.fit(train_images, train_labels, epochs=100, batch_size=512)

Epoch 1/100
60000/60000 [==============================] - 15s 251us/step - loss: 0.3989 - acc: 0.8873
Epoch 2/100
60000/60000 [==============================] - 0s 8us/step - loss: 0.1759 - acc: 0.9496
Epoch 3/100
60000/60000 [==============================] - 0s 8us/step - loss: 0.1201 - acc: 0.9653
Epoch 4/100
60000/60000 [==============================] - 1s 9us/step - loss: 0.0886 - acc: 0.9747
Epoch 5/100
60000/60000 [==============================] - 1s 9us/step - loss: 0.0692 - acc: 0.9798
Epoch 6/100
60000/60000 [==============================] - 1s 9us/step - loss: 0.0550 - acc: 0.9839
Epoch 7/100
60000/60000 [==============================] - 1s 11us/step - loss: 0.0443 - acc: 0.9875
Epoch 8/100
60000/60000 [==============================] - 1s 9us/step - loss: 0.0360 - acc: 0.9903
Epoch 9/100
60000/60000 [==============================] - 0s 8us/step - loss: 0.0294 - acc: 0.9920
Epoch 10/100
60000/60000 [==============================] - 1s 8us/step - loss: 0.0236 - acc: 0.

60000/60000 [==============================] - 0s 8us/step - loss: 1.6726e-07 - acc: 1.0000
Epoch 81/100
60000/60000 [==============================] - 0s 8us/step - loss: 1.6593e-07 - acc: 1.0000
Epoch 82/100
60000/60000 [==============================] - 0s 8us/step - loss: 1.6332e-07 - acc: 1.0000
Epoch 83/100
60000/60000 [==============================] - 0s 8us/step - loss: 1.6132e-07 - acc: 1.0000
Epoch 84/100
60000/60000 [==============================] - 0s 8us/step - loss: 1.5976e-07 - acc: 1.0000
Epoch 85/100
60000/60000 [==============================] - 0s 8us/step - loss: 1.5800e-07 - acc: 1.0000
Epoch 86/100
60000/60000 [==============================] - 0s 8us/step - loss: 1.5641e-07 - acc: 1.0000
Epoch 87/100
60000/60000 [==============================] - 0s 8us/step - loss: 1.5503e-07 - acc: 1.0000
Epoch 88/100
60000/60000 [==============================] - 0s 8us/step - loss: 1.5381e-07 - acc: 1.0000
Epoch 89/100
60000/60000 [==============================] - 0s 8us/s

In [18]:
test_loss, test_acc=network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 1s 64us/step


In [19]:
print("test_loss: ", test_loss," test_acc: ",test_acc)

test_loss:  0.11948678169908374  test_acc:  0.9835


In [24]:
op=network.predict(test_images)

In [25]:
print(op[1])

[4.44289328e-31 2.03777414e-20 1.00000000e+00 2.85414517e-27
 0.00000000e+00 3.47866071e-29 1.17351245e-27 0.00000000e+00
 3.10548134e-27 0.00000000e+00]


In [26]:
test_labels[1]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)